#!/bin/sh
# Configure system defaults

/etc/init.d/odhcpd disable
/etc/init.d/firewall disable

chmod 600 /etc/dropbear/authorized_keys
chmod a+x /etc/init.d/hostapd_wlan2

ADDR=$(cat /sys/class/net/eth1/address)
MYHOSTNAME=$(echo T${ADDR:9:9} | sed 's/://g')

# Set Host configuration 
uci -q batch <<-EOT

  set system.@system[0].timezone='CET-1CEST,M3.5.0,M10.5.0/3'
  set system.@system[0].hostname=$MYHOSTNAME

  # Ignore DHCPD on LAN
  set dhcp.lan.ignore=1
  
  # Configure LAN
  del network.lan.type
  set network.lan.proto='dhcp'

  add network interface
  rename network.@interface[-1]='lan_default'
  set network.lan_default.ifname='eth1'
  set network.lan_default.proto='static'
  set network.lan_default.ipaddr='192.168.0.1'
  set network.lan_default.netmask='255.255.255.0'

  add network interface
  rename network.@interface[-1]='lan6'
  set network.lan6.ifname='eth1'
  set network.lan6.proto='dhcpv6'
  set network.lan6.ip6ifaceid 'random'
  set network.lan6.ip6hint '0d0d'
  set network.lan6.ip6assign '64'

  # Configure WLAN0
  set wireless.@wifi-device[0].disabled='0'
  set wireless.@wifi-iface[0].mode='sta'
  set wireless.@wifi-iface[0].network='wlan0'
  set wireless.@wifi-iface[0].ifname='wlan0'

  add network interface
  rename network.@interface[-1]='wlan0'
  set network.wlan0.ifname='wlan0'
  set network.wlan0.proto='dhcp'

  # Configure WLAN1
  set wireless.@wifi-device[1].disabled='0'
  set wireless.@wifi-iface[1].mode='sta'
  set wireless.@wifi-iface[1].network='wlan1'
  set wireless.@wifi-iface[1].ifname='wlan1'

  add network interface
  rename network.@interface[-1]='wlan1'
  set network.wlan1.ifname='wlan1'
  set network.wlan1.proto='dhcp'

  # Configure WLAN2
  del wireless.@wifi-device[2].hwmode
  del wireless.@wifi-device[2].htmode
  del wireless.@wifi-device[2].channel
  set wireless.@wifi-device[2].freq='60480'
  set wireless.@wifi-device[2].disabled='0'
  set wireless.@wifi-iface[2].mode='sta'
  set wireless.@wifi-iface[2].network='wlan2'
  set wireless.@wifi-iface[2].ifname='wlan2'
  set wireless.@wifi-iface[2].ssid='TALON_AD7200'
  set wireless.@wifi-iface[2].encryption='none'

  add network interface
  rename network.@interface[-1]='wlan2'
  set network.wlan2.ifname='wlan2'
  set network.wlan2.proto='static'
  set network.wlan2.ipaddr='192.168.100.1'
  set network.wlan2.netmask='255.255.255.0'

  add network interface
  rename network.@interface[-1]='wlan2_6'
  set network.wlan2_6.proto='static'
  set network.wlan2_6.ip6ifaceid 'random'
  set network.wlan2_6.ip6hint '0d0d'
  set network.wlan2_6.ip6assign '64'

  commit dhcp
  commit wireless
  commit network
  commit

  EOT

wifi
/etc/init.d/network restart

exit 0
